<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $vendorId = 2;

        $products = [
            [
                'vendor_id' => $vendorId,
                'name' => 'Pork Belly (Liempo)',
                'description' => 'Fresh pork belly, perfect for grilling or inihaw. Sourced daily from local farms.',
                'category' => 'Meat',
                'price' => 320.00,
                'unit' => 'kg',
                'stock_quantity' => 25,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Pork Kasim',
                'description' => 'Lean pork shoulder cut, great for adobo and sinigang.',
                'category' => 'Meat',
                'price' => 280.00,
                'unit' => 'kg',
                'stock_quantity' => 18,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Ground Pork',
                'description' => 'Freshly ground pork for lumpia, embotido, and other dishes.',
                'category' => 'Meat',
                'price' => 290.00,
                'unit' => 'kg',
                'stock_quantity' => 12,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Beef Brisket',
                'description' => 'Tender beef brisket ideal for bulalo, nilaga, and slow-cooked stews.',
                'category' => 'Meat',
                'price' => 380.00,
                'unit' => 'kg',
                'stock_quantity' => 8,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Whole Dressed Chicken',
                'description' => 'Farm-fresh whole chicken, cleaned and ready to cook.',
                'category' => 'Poultry',
                'price' => 195.00,
                'unit' => 'kg',
                'stock_quantity' => 30,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Chicken Wings',
                'description' => 'Party-ready chicken wings, great for frying or grilling.',
                'category' => 'Poultry',
                'price' => 210.00,
                'unit' => 'kg',
                'stock_quantity' => 15,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Fresh Tilapia',
                'description' => 'Farm-raised tilapia, medium size. Perfect for sinigang or fried.',
                'category' => 'Fish',
                'price' => 150.00,
                'unit' => 'kg',
                'stock_quantity' => 20,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Bangus (Milkfish)',
                'description' => 'Boneless bangus, vacuum packed. Ready for daing or sinigang.',
                'category' => 'Fish',
                'price' => 220.00,
                'unit' => 'kg',
                'stock_quantity' => 10,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Shrimp (Suahe)',
                'description' => 'Small fresh shrimp, ideal for pancit, sinigang, or tempura.',
                'category' => 'Seafood',
                'price' => 450.00,
                'unit' => 'kg',
                'stock_quantity' => 5,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Squid (Pusit)',
                'description' => 'Fresh whole squid, great for adobong pusit or calamares.',
                'category' => 'Seafood',
                'price' => 350.00,
                'unit' => 'kg',
                'stock_quantity' => 7,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Kangkong Bundle',
                'description' => 'Fresh water spinach, locally grown. Staple for adobo and sinigang.',
                'category' => 'Vegetables',
                'price' => 15.00,
                'unit' => 'bundle',
                'stock_quantity' => 50,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Pechay (Bok Choy)',
                'description' => 'Crisp pechay leaves, great for soups, stir-fry, and nilaga.',
                'category' => 'Vegetables',
                'price' => 20.00,
                'unit' => 'bundle',
                'stock_quantity' => 40,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Sitaw (String Beans)',
                'description' => 'Long beans, fresh from the farm. Perfect for pinakbet and kare-kare.',
                'category' => 'Vegetables',
                'price' => 25.00,
                'unit' => 'bundle',
                'stock_quantity' => 35,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Ripe Mango (Carabao)',
                'description' => 'Sweet Philippine carabao mango, ripe and ready to eat.',
                'category' => 'Fruits',
                'price' => 120.00,
                'unit' => 'kg',
                'stock_quantity' => 0,
                'is_available' => false,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Banana (Lakatan)',
                'description' => 'Sweet lakatan bananas, sold by the dozen.',
                'category' => 'Fruits',
                'price' => 60.00,
                'unit' => 'dozen',
                'stock_quantity' => 22,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Garlic (Bawang)',
                'description' => 'Imported garlic, strong aroma. Essential for Filipino cooking.',
                'category' => 'Spices',
                'price' => 180.00,
                'unit' => 'kg',
                'stock_quantity' => 15,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Red Onion (Sibuyas)',
                'description' => 'Local red onions, medium size. Sold per kilo.',
                'category' => 'Spices',
                'price' => 160.00,
                'unit' => 'kg',
                'stock_quantity' => 3,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Fresh Eggs (Medium)',
                'description' => 'Farm-fresh eggs, medium size. Sold per tray of 30.',
                'category' => 'Dairy',
                'price' => 210.00,
                'unit' => 'pack',
                'stock_quantity' => 10,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Jasmine Rice (5kg)',
                'description' => 'Premium jasmine rice, fragrant and fluffy when cooked.',
                'category' => 'Grains & Rice',
                'price' => 295.00,
                'unit' => 'pack',
                'stock_quantity' => 40,
                'is_available' => true,
            ],
            [
                'vendor_id' => $vendorId,
                'name' => 'Soy Sauce (Toyo) 1L',
                'description' => 'Silver Swan soy sauce, 1 liter bottle. Kitchen staple.',
                'category' => 'Condiments',
                'price' => 55.00,
                'unit' => 'pcs',
                'stock_quantity' => 0,
                'is_available' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
